<?php

echo $this->inlineScript()
    ->prependFile($this->basePath() . '/js/datehelper.js');

    $url = $this->url('app/ia', ['controller' => 'ia', 'action' => 'cadastrar']);
?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Cadastrar a IA</h4>
                </div>
                <div class="content">
                    <form method="post" action="<?= $url; ?>">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Data da Inseminação</label>
                                    <input type="text"
                                           class="form-control border-input validate-date"
                                           name="dataInseminacao"
                                           placeholder="Dia/Mês/Ano"
                                           data-mask="00/00/0000"
                                           oninvalid="this.setCustomValidity('Insira uma data válida no formato: Dia/Mês/Ano')"
                                           oninput="setCustomValidity('')"
                                           required/>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Número da Vaca</label>
                                    <input type="text"
                                           class="form-control border-input validate-date"
                                           name="numeroDaVaca"
                                           placeholder="Número da Vaca"
                                           pattern="[0-9]"
                                           oninvalid="this.setCustomValidity('Insira um número válido')"
                                           oninput="setCustomValidity('')"
                                           required/>
                                </div>
                            </div>
                        </div>

                        <div class="text-center ">
                            <button type="submit" class="btn btn-info btn-fill btn-wd">Cadastrar</button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>