<?php echo $this->render("cadastrar.phtml");?>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Todos as IAs</h4>
                </div>
                <div class="content">
                    <table id="ias" class="table table-hover display" style="width:100%">
                        <thead>
                        <tr>
                            <th hidden>#</th>
                            <th>Número</th>
                            <th>Data da Inseminação</th>
                            <th>Opções</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php foreach ($ias as $ia) { ?>
                            <tr>
                                <td hidden><?= $ia->getId(); ?></td>
                                <td><?= $ia->getAnimal()->getNumero(); ?></td>
                                <td><?= $ia->getDataInseminacaoToString(); ?></td>

                                <td>
                                    <a type="button"
                                       href="<?= $this->url('app/ia', ['action' => 'editar', 'id' => $ia->getId()]) ?>"
                                       class="btn btn-info btn-fill">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </a>

                                    <a href="<?= $this->url('app/ia', ['action' => 'remover', 'id' => $ia->getId()]) ?>"
                                       class="btn btn-danger btn-fill">
                                        <i class="fa fa-trash" aria-hidden="true" type="hidden"></i>
                                    </a>
                                </td>


                            </tr>

                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(function ($) {
        $('#ias').DataTable({
            columnDefs: [
                {targets: '_all', className: 'dt-center'},
                { "orderable": false, "targets": 3 },
            ],
            aoColumns: [
                null,
                null,
                {"sType": "date-uk"},
                null
            
            ],
            order: [[2, 'desc']],
            paging: false
            
        });

        $('#ias_filter label input').addClass('form-control border-input');

    });

</script>

