<?php

echo $this->headLink()->prependStylesheet($this->basePath() . '/css/data-tables/dataTables.bootstrap.min.css');
echo $this->headLink()->prependStylesheet($this->basePath() . '/css/data-tables/datatables.min.css');
echo $this->inlineScript()->prependFile($this->basePath() . '/js/data-tables/jquery.dataTables.min.js');
echo $this->inlineScript()->prependFile($this->basePath() . '/js/data-tables/dataTables.bootstrap.min.js');

?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Estações</h4>
                </div>
                <div class="content">
                    <table id="animais" class="table table-hover display" style="width:100%">
                        <thead>
                        <tr>
                            <th style="display: none">#</th>
                            <th>Data de Início</th>
                            <th>Data de Término</th>
                            <th>Quantidade de Animais</th>
                            <th>Animais</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php
                        foreach ($estacoes as $estacao) { ?>

                            <tr>
                                <td style="display: none"><?= $estacao->getId(); ?></td>
                                <td><?= $estacao->getDataInicialString(); ?></td>
                                <td><?= $estacao->getDataFinalString(); ?></td>
                                <td><?= $estacao->getAnimal()->count(); ?></td>

                                <td>
                                    <a type="button"
                                       href="<?= $this->url('app/estacao', ['action' => 'listar', 'id' => $estacao->getId()]) ?>"
                                       class="btn btn-info btn-fill">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </a>
                                </td>


                            </tr>

                            <?php
                        }
                        ?>


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(function ($) {
        $('#animais').DataTable({
            columnDefs: [
                { targets: '_all', className: 'dt-center' }
            ],
            order: [[2, 'desc']],
            paging: false
        });

        $('#animais_filter label input').addClass('form-control border-input');
    });
</script>

