<?php

echo $this->headLink()->prependStylesheet($this->basePath() . '/css/data-tables/dataTables.bootstrap.min.css');
echo $this->headLink()->prependStylesheet($this->basePath() . '/css/data-tables/datatables.min.css');
echo $this->inlineScript()->prependFile($this->basePath() . '/js/data-tables/jquery.dataTables.min.js');
echo $this->inlineScript()->prependFile($this->basePath() . '/js/data-tables/dataTables.bootstrap.min.js');

?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Animais da Estação</h4>
                </div>
                <div class="content">
                    <table id="animais" class="table table-hover display" style="width:100%">
                        <thead>
                        <tr>
                            <th style="display: none">#</th>
                            <th>Número</th>
                            <th>Classificação</th>
                            <th>Data do Último Parto</th>
                            <th>Opções</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php
                        foreach ($animais as $animal) { ?>

                            <tr>
                                <td style="display: none"><?= $animal->getId(); ?></td>
                                <td><?= $animal->getNumero(); ?></td>
                                <td><?= $animal->getClassificacao(); ?></td>
                                <td><?= $animal->dataUltimoPartoToString(); ?></td>

                                <td>
                                    <a class="btn btn-info btn-fill" type="button"
                                       href="<?= $this->url('app/animal', [
                                           'action' => 'editar',
                                           'id' => $animal->getId()]) ?>"
                                    >
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </a>

                                    <a class="btn btn-danger btn-fill" href="<?= $this->url('app/estacao', [
                                        'action' => 'remover-animal',
                                        'id' => $animal->getId(),
                                        'eid' => basename($_SERVER['REQUEST_URI'])]) ?>"
                                    >
                                        <i class="fa fa-trash" aria-hidden="true" type="hidden"></i>
                                    </a>
                                </td>


                            </tr>

                            <?php
                        }
                        ?>


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(function ($) {
        $('#animais').DataTable({
            columnDefs: [
                {targets: '_all', className: 'dt-center'}
            ],
            order: [[3, 'desc']],
            paging: false
        });

        $('#animais_filter label input').addClass('form-control border-input');
    });
</script>
