<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="icon-big text-center">
                                <img src="<?= $this->basePath() . '/img/paper-dashboard/cards/cow.png'; ?>"
                                     width="42px" height="42px">
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="numbers">
                                <p>Aptos</p>
                                <?= sizeof($animaisAptos); ?>
                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <hr/>
                        <div class="stats">
                            <i class="fa fa-info" aria-hidden="true"></i>
                            <?php if (sizeof($animaisAptos) > 0) { ?>
                                <a data-toggle="modal" href="#modalAptos">Detalhes dos Animais</a>
                            <?php } else { ?>
                                Detalhes dos Animais
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="icon-big text-center">
                                <img src="<?= $this->basePath() . '/img/paper-dashboard/cards/stethoscope1.png'; ?>"
                                     width="50px" height="50px">
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="numbers">
                                <p>Diagnóstico 1</p>
                                <?= sizeof($animaisD1); ?>
                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <hr/>
                        <div class="stats">
                            <i class="fa fa-info" aria-hidden="true"></i>
                            <?php if (sizeof($animaisD1) > 0) { ?>
                                <a data-toggle="modal" href="#modalDiagnostico1">Detalhes dos Animais</a>
                            <?php } else { ?>
                                Detalhes dos Animais
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="icon-big text-center">
                                <img src="<?= $this->basePath() . '/img/paper-dashboard/cards/stethoscope2.png'; ?>"
                                     width="50px" height="50px">
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="numbers">
                                <p>Diagnóstico 2</p>
                                <?= sizeof($animaisD2); ?>
                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <hr/>
                        <div class="stats">
                            <i class="fa fa-info" aria-hidden="true"></i>
                            <?php if (sizeof($animaisD2) > 0) { ?>
                                <a data-toggle="modal" href="#modalDiagnostico2">Detalhes dos Animais</a>
                            <?php } else { ?>
                                Detalhes dos Animais
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="icon-big text-center">
                                <i class="fa fa-calendar-times-o" aria-hidden="true"></i>
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="numbers">
                                <p>Pós-Parto</p>
                                <?= sizeof($animaisPosParto); ?>
                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <hr/>
                        <div class="stats">
                            <i class="fa fa-info" aria-hidden="true"></i>
                            <?php if (sizeof($animaisPosParto) > 0) { ?>
                                <a data-toggle="modal" href="#modalPosParto">Detalhes dos Animais</a>
                            <?php } else { ?>
                                Detalhes dos Animais
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Users Behavior</h4>
                    <p class="category">24 Hours performance</p>
                </div>
                <div class="content">
                    <div id="chartHours" class="ct-chart"></div>
                    <div class="footer">
                        <div class="chart-legend">
                            <i class="fa fa-circle text-info"></i> Open
                            <i class="fa fa-circle text-danger"></i> Click
                            <i class="fa fa-circle text-warning"></i> Click Second Time
                        </div>
                        <hr>
                        <div class="stats">
                            <i class="ti-reload"></i> Updated 3 minutes ago
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="header">
                    <h4 class="title">Email Statistics</h4>
                    <p class="category">Last Campaign Performance</p>
                </div>
                <div class="content">
                    <div id="chartPreferences" class="ct-chart ct-perfect-fourth"></div>

                    <div class="footer">
                        <div class="chart-legend">
                            <i class="fa fa-circle text-info"></i> Open
                            <i class="fa fa-circle text-danger"></i> Bounce
                            <i class="fa fa-circle text-warning"></i> Unsubscribe
                        </div>
                        <hr>
                        <div class="stats">
                            <i class="ti-timer"></i> Campaign sent 2 days ago
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card ">
                <div class="header">
                    <h4 class="title">2015 Sales</h4>
                    <p class="category">All products including Taxes</p>
                </div>
                <div class="content">
                    <div id="chartActivity" class="ct-chart"></div>

                    <div class="footer">
                        <div class="chart-legend">
                            <i class="fa fa-circle text-info"></i> Tesla Model S
                            <i class="fa fa-circle text-warning"></i> BMW 5 Series
                        </div>
                        <hr>
                        <div class="stats">
                            <i class="ti-check"></i> Data information certified
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="modals">
    <!-- Modal dos Animais Aptos-->
    <div class="modal fade" id="modalAptos" tabindex="-1" role="dialog" aria-labelledby="modalAptosLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Animais Aptos</h4>
                </div>
                <div class="modal-body">
                    <div class="table-responsive">
                        <table class="table table-borderless">
                            <thead>
                            <tr>
                                <th class="text-center"><b>Número</b></th>
                            </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($animaisAptos as $a) { ?>
                                    <tr class="text-center">
                                        <td><?= $a->getNumero(); ?></td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal dos Animais Aguardando Diagnóstico 1-->
    <div class="modal fade" id="modalDiagnostico1" tabindex="-1" role="dialog" aria-labelledby="modalDiagnostico1Label"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title text-center">Animais Aguardando o Diagnóstico 1</h4>
                </div>
                <div class="modal-body">
                    <div class="table-responsive">
                        <table class="table table-borderless">
                            <thead>
                            <tr>
                                <th class="text-center"><b>Nº do Animal</b></th>
                                <th class="text-center"><b>Protocolo</b></th>
                                <th class="text-center"><b>Data do Diagnóstico 1</b></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($animaisD1 as $a) { ?>
                                <?php  if (!is_null($a->getUltimaIA()->getProtocolo())) { ?>
                                    <tr class="text-center">
                                        <td><?= $a->getNumero(); ?></td>
                                        <td><?= 'Protocolo ' . $a->getUltimaIA()->getProtocolo()->getNumero(); ?></td>
                                        <td><?= \Application\Helper\Data::dataToString($a->getUltimaIA()->getDataDiagnostico1()); ?></td>
                                    </tr>
                                <?php } ?>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal dos Animais Aguardando Diagnóstico 2-->
    <div class="modal fade" id="modalDiagnostico2" tabindex="-1" role="dialog" aria-labelledby="modalDiagnostico2Label"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title text-center">Animais Aguardando o Diagnóstico 2</h4>
                </div>
                <div class="modal-body">
                    <div class="table-responsive">
                        <table class="table table-borderless">
                            <thead>
                            <tr>
                                <th class="text-center"><b>Nº do Animal</b></th>
                                <th class="text-center"><b>Protocolo</b></th>
                                <th class="text-center"><b>Data do Diagnóstico 2</b></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($animaisD2 as $a) { ?>
                                <?php  if (!is_null($a->getUltimaIA()->getProtocolo())) { ?>
                                    <tr class="text-center">
                                        <td><?= $a->getNumero(); ?></td>
                                        <td><?= 'Protocolo ' . $a->getUltimaIA()->getProtocolo()->getNumero(); ?></td>
                                        <td><?= \Application\Helper\Data::dataToString($a->getUltimaIA()->getDataDiagnostico2()); ?></td>
                                    </tr>
                                <?php } ?>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal dos Animais em Pós-Parto-->
    <div class="modal fade" id="modalPosParto" tabindex="-1" role="dialog" aria-labelledby="modalPosParto"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title text-center">Animais no Pós-Parto</h4>
                </div>
                <div class="modal-body">
                    <div class="table-responsive">
                        <table class="table table-borderless">
                            <thead>
                            <tr>
                                <th class="text-center"><b>Número</b></th>
                                <th class="text-center"><b>Dias Desde o Último Parto</b></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($animaisPosParto as $a) { ?>
                                <tr class="text-center">
                                    <td><?= $a->getNumero(); ?></td>
                                    <td><?= $a->getDiasDesdeUltimoParto(); ?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
echo $this->inlineScript()->prependFile($this->basePath() . '/js/dashboard/dashboard.js');
?>

<script type="text/javascript">
    $(document).ready(function () {

        demo.initChartist();

        $.notify({
            icon: 'ti-gift',
            message: "Welcome to <b>MyTree</b> - Under Construction."

        }, {
            type: 'success',
            timer: 4000
        });

    });
</script>
