<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Relatórios</h4>
                </div>
                <div class="content">
                    <ul>
                        <li>
                            <a href="<?= $this->url('app/relatorio', array('controller' => 'relatorio', 'action' => 'txPrenhezNovilhas')); ?>">
                                Comparação da Taxa de Prenhez entre Novilhas Induzidas X Não Induzidas
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url('app/relatorio', array('controller' => 'relatorio', 'action' => 'txPrenhezProtocolo')); ?>">
                                Taxa de Prenhez Geral por Protocolo
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>