<?php //$url = $this->url('app/protocolo', ['controller' => 'protocolo', 'action' => 'cadastrar']); ?>
<?php //$this->headLink()->appendStylesheet($this->basePath() . '/css/protocolo/protocolo.css'); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Relatórios</h4>
                </div>
                <div class="content">

                </div>
            </div>
        </div>
    </div>
</div>

<?php
//echo $this->inlineScript()->prependFile($this->basePath() . '/js/protocolo/protocolo.js');
//echo $this->inlineScript()->prependFile($this->basePath() . '/js/datehelper.js');
?>