<div class="container-fluid">
    <?php echo $this->flashHelper(); ?>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Protocolos de Induções</h4>
                </div>
                <div class="content">
                    <table id="animais" class="table table-hover display" style="width:100%">
                        <thead>
                        <tr>
                            <th hidden>#</th>
                            <th>Nº Indução</th>
                            <th>Início</th>
                            <th>Fim</th>
                            <th>Dias desde a Indução</th>
                            <th>Mais Informações</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($inducoes as $inducao) { ?>
                            <?php  if (!is_null($inducao)) { ?>
                            <tr>
                                <td hidden><?= $inducao->getId(); ?></td>
                                <td><b><?= $inducao->getId();?></b></td>
                                <td><?= \Application\Helper\Data::dataToString($inducao->getDataInicio()); ?></td>
                                <td><?= \Application\Helper\Data::dataToString($inducao->getDataFinal()); ?></td>
                                <td><?= $inducao->getDiasDaInducao(); ?></td>
                                <td>
                                    <a type="button"
                                       href="<?= $this->url('app/inducao', ['action' => 'listar', 'id' => $inducao->getId()]) ?>"
                                       class="btn btn-info btn-fill">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </a>
                            <?php }; ?>
                                </td>
                            </tr>

                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(function ($) {
        $('#animais').DataTable({
            columnDefs: [
                {"orderable": false, "targets": 0},
                {"orderData": [6], "targets": [2]},
                {targets: '_all', className: 'dt-center'},
            ],
            aoColumns: [
                null,
                null,
                {"sType": "date-uk"},
                {"sType": "date-uk"},
                null,
                null,
            ],
            order: [[0, 'desc']],
            paging: false
        });

        $('#animais_filter label input').addClass('form-control border-input');
    });
</script>