<?php $url = $this->url('app/protocolo', ['controller' => 'protocolo', 'action' => 'cadastrar']); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Cadastrar um Protocolo</h4>
                </div>
                <div class="content">
                    <form method="post" action="<?= $url; ?>">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Número do Protocolo</label>
                                    <input type="number"
                                           class="form-control border-input"
                                           name="numeroDoProtocolo"
                                           placeholder="Número do Protocolo"
                                           pattern="[0-9]"
                                           oninvalid="this.setCustomValidity('Insira um número válido')"
                                           oninput="setCustomValidity('')"
                                           required/>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Estação</label>
                                    <select class="form-control border-input" id="sel1" name="idEstacao">
                                        <?php if (!is_null($estacao)) { ?>
                                            <option value="<?= $estacao->getId(); ?>">
                                                <?= \Application\Helper\Data::dataToString($estacao->getDataInicio()); ?>
                                                até
                                                <?= \Application\Helper\Data::dataToString($estacao->getDataFinal()); ?>
                                            </option>

                                        <?php } else { ?>
                                            <option>
                                                -
                                            </option>

                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Data de Inseminação</label>
                                    <input type="text"
                                           class="form-control border-input validate-date"
                                           name="dataDeInseminacao"
                                           placeholder="Dia/Mês/Ano"
                                           data-mask="00/00/0000"
                                           oninvalid="this.setCustomValidity('Insira uma data válida no formato: Dia/Mês/Ano')"
                                           oninput="setCustomValidity('')"
                                           required/>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Data de Retorno ao Cio</label>
                                    <input type="text"
                                           class="form-control border-input validate-date"
                                           name="dataDeRetornoAoCio"
                                           placeholder="Dia/Mês/Ano"
                                           data-mask="00/00/0000"
                                           oninvalid="this.setCustomValidity('Insira uma data válida no formato: Dia/Mês/Ano')"
                                           oninput="setCustomValidity('')"
                                           required/>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Data de Diagnóstico 1</label>
                                    <input type="text"
                                           class="form-control border-input validate-date"
                                           name="dataDeDiagnostico1"
                                           placeholder="Dia/Mês/Ano"
                                           data-mask="00/00/0000"
                                           oninvalid="this.setCustomValidity('Insira uma data válida no formato: Dia/Mês/Ano')"
                                           oninput="setCustomValidity('')"
                                           required/>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Data de Diagnóstico 2</label>
                                    <input type="text"
                                           class="form-control border-input validate-date"
                                           name="dataDeDiagnostico2"
                                           placeholder="Dia/Mês/Ano"
                                           data-mask="00/00/0000"
                                           oninvalid="this.setCustomValidity('Insira uma data válida no formato: Dia/Mês/Ano')"
                                           oninput="setCustomValidity('')"
                                           required/>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label style="font-size: 16px;">Animais do Protocolo</label>
                                    <table id="animais" class="table table-hover display" style="width:100%">
                                        <thead>
                                        <tr>
                                            <th></th>
                                            <th hidden>ID</th>
                                            <th>Número</th>
                                            <th>Classificação</th>
                                            <th>Estado</th>
                                            <th>Dias Desde o Último Parto</th>
                                            <th hidden>Dias Desde o Último Parto - Sort</th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        <?php foreach ($animais as $animal) { ?>

                                            <?php if ($animal->getDiasDesdeUltimoParto() < 40 && $animal->getDiasDesdeUltimoParto() != "-") { ?>

                                                <tr class="text-danger">
                                                <td>
                                                    <div class="checkbox">
                                                        <input class="input-checkbox" type="checkbox"/>
                                                    </div>
                                                </td>

                                            <?php } else { ?>
                                                <tr>
                                                <td>
                                                    <div class="checkbox">
                                                        <input class="input-checkbox" type="checkbox" checked/>
                                                    </div>
                                                </td>
                                            <?php } ?>

                                            <td class="idAnimal" style="display: none"><?= $animal->getId(); ?></td>
                                            <td><?= $animal->getNumero(); ?></td>
                                            <td><?= $animal->getClassificacao(); ?></td>
                                            <td><?= $animal->getEstado(); ?></td>
                                            <td><?= $animal->getDiasDesdeUltimoParto(); ?></td>
                                            <td hidden>
                                                <?php
                                                if ($animal->getDiasDesdeUltimoParto() == "-")
                                                    echo "9999";
                                                else
                                                    echo $animal->getDiasDesdeUltimoParto();
                                                ?>
                                            </td>

                                            </tr>

                                        <?php } ?>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                        <!-- Lista de Animais -->
                        <input hidden name="lsIDsAnimais" required/>

                        <div class="text-center ">
                            <button type="submit" class="btn btn-info btn-fill btn-wd">Cadastrar</button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
echo $this->inlineScript()->prependFile($this->basePath() . '/js/protocolo/protocolo.js');
echo $this->inlineScript()->prependFile($this->basePath() . '/js/datehelper.js');
?>

<script>

    jQuery(function ($) {
        $('#animais').DataTable({
            columnDefs: [
                {"orderable": false, "targets": 0},
                {targets: '_all', className: 'dt-center'},
                {"orderData": [6], "targets": [5]}
            ],
            order: [[5, 'asc']],
            paging: false,
            searching: false
        });
    });

</script>