<div class="container-fluid">
    <?php echo $this->flashHelper(); ?>

    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Protocolos</h4>
                </div>
                <div class="content">
                    <table id="animais" class="table table-hover display" style="width:100%">
                        <thead>
                        <tr>
                            <th>Nº Protocolo</th>
                            <th>Inseminação</th>
                            <th>Retorno ao Cio</th>
                            <th>Diagnóstico 1</th>
                            <th>Diagnóstico 2</th>
                            <th>Detalhes</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php foreach ($ias as $ia) { ?>

                            <tr>
                                <td><?= $ia->getNumeroProtocolo(); ?></td>
                                <td><?= $ia->dataToString($ia->getDataInseminacao()); ?></td>
                                <td><?= $ia->dataToString($ia->getDataRetornoAoCio()); ?></td>
                                <td><?= $ia->dataToString($ia->getDataDiagnostico1()); ?></td>
                                <td><?= $ia->dataToString($ia->getDataDiagnostico2()); ?></td>
                                <td>
                                    <a type="button"
                                       href="<?= $this->url('app/protocolo', ['action' => 'listar', 'id' => $ia->getNumeroProtocolo()]) ?>"
                                       class="btn btn-info btn-fill">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </a>
                                </td>
                            </tr>

                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(function ($) {
        $('#animais').DataTable({
            columnDefs: [
                { "orderable": false, "targets": 5 },
                {targets: '_all', className: 'dt-center'},
            ],
            aoColumns: [
                null,
                {"sType": "date-uk"},
                {"sType": "date-uk"},
                {"sType": "date-uk"},
                {"sType": "date-uk"},
                null
            ],
            order: [[0, 'desc']],
            paging: false
        });

        $('#animais_filter label input').addClass('form-control border-input');
    });
</script>

