<div class="container-fluid">
    <?php echo $this->flashHelper(); ?>

    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Protocolos</h4>
                </div>
                <div class="content">
                    <table id="animais" class="table table-hover display" style="width:100%">
                        <thead>
                        <tr>
                            <th>Nº Protocolo</th>
                            <th>Data da Inseminação</th>
                            <th>Data do Próximo Diagnóstico</th>
                            <th hidden>Data do Próximo Diagnóstico - Sort</th>
                            <th>Estado</th>
                            <th>Alterar Estado</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php foreach ($ias as $ia) { ?>
                            <?php  if (!is_null($ia->getProtocolo())) { ?>
                            <tr>
                                <td><b><?= $ia->getProtocolo()->getNumero(); ?></b></td>
                                <td><?= \Application\Helper\Data::dataToString($ia->getDataInseminacao()); ?></td>

                                <td>
                                    <?php if ($ia->getProtocolo()->getEstado()->getEstado() == 'Aguardando Diagnóstico 1') { ?>
                                        <?= \Application\Helper\Data::dataToString($ia->getDataDiagnostico1()); ?>

                                    <?php } else if ($ia->getProtocolo()->getEstado()->getEstado() == 'Aguardando Diagnóstico 2') { ?>
                                        <?= \Application\Helper\Data::dataToString($ia->getDataDiagnostico2()); ?>

                                    <?php } else { ?>
                                        -
                                    <?php }; ?>
                                </td>

                                <td hidden>
                                    <?php if ($ia->getProtocolo()->getEstado()->getEstado() == 'Aguardando Diagnóstico 1') { ?>
                                        <?= \Application\Helper\Data::dataToString($ia->getDataDiagnostico1()); ?>

                                    <?php } else if ($ia->getProtocolo()->getEstado()->getEstado() == 'Aguardando Diagnóstico 2') { ?>
                                        <?= \Application\Helper\Data::dataToString($ia->getDataDiagnostico2()); ?>

                                    <?php } else { ?>
                                        00/00/0000

                                    <?php }; ?>
                                </td>

                                <td>
                                    <?php if ($ia->getProtocolo()->getEstado()->getEstado() == 'Gestante') { ?>
                                        <i class="text-success">Finalizado</i>
                                        <i class="fa fa-check text-success" aria-hidden="true"></i>
                                    <?php } else if($ia->getProtocolo()->getEstado()->getEstado() == 'Apto'){ ?>
                                            <i class="text-danger">Falhou</i>
                                            <i class="fa fa-close text-danger" aria-hidden="true"></i>
                                    <?php }else{ ?>
                                            <i><?= $ia->getProtocolo()->getEstado()->getEstado(); ?></i>
                                    <?php } ?>
                                </td>

                                <td>
                                    <a type="button"
                                       href="<?= $this->url('app/protocolo', ['action' => 'listar', 'id' => $ia->getProtocolo()->getNumero()]) ?>"
                                       class="btn btn-info btn-fill">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </a>
                            <?php }; ?>
                                </td>
                            </tr>

                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(function ($) {
        $('#animais').DataTable({
            columnDefs: [
                {"orderable": false, "targets": 5},
                {"orderData": [3], "targets": [2]},
                {targets: '_all', className: 'dt-center'},
            ],
            aoColumns: [
                null,
                {"sType": "date-uk"},
                {"sType": "date-uk"},
                {"sType": "date-uk"},
                null,
                null
            ],
            order: [[0, 'desc']],
            paging: false
        });

        $('#animais_filter label input').addClass('form-control border-input');
    });
</script>

