<?php
    $url = $this->url('app/animal', ['controller' => 'animal', 'action' => 'cadastro']);
?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 col-md-5">
            <div class="card card-user">
                <div class="image">
                    <img src="<?= $this->basePath() . '/img/paper-dashboard/background.jpg'; ?>" alt="..."/>
                </div>
                <div class="content">
                    <div class="author">
                        <img class="avatar border-white"
                             src="<?= $this->basePath() . '/img/paper-dashboard/faces/face-2.jpg'; ?>" alt="..."/>
                        <h4 class="title">Chet Faker<br/>
                            <a href="#">
                                <small>@chetfaker</small>
                            </a>
                        </h4>
                    </div>
                    <p class="description text-center">
                        "I like the way you work it <br>
                        No diggity <br>
                        I wanna bag it up"
                    </p>
                </div>
                <hr>
                <div class="text-center">
                    <div class="row">
                        <div class="col-md-3 col-md-offset-1">
                            <h5>12<br/>
                                <small>Files</small>
                            </h5>
                        </div>
                        <div class="col-md-4">
                            <h5>2GB<br/>
                                <small>Used</small>
                            </h5>
                        </div>
                        <div class="col-md-3">
                            <h5>24,6$<br/>
                                <small>Spent</small>
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="header">
                    <h4 class="title">Team Members</h4>
                </div>
                <div class="content">
                    <ul class="list-unstyled team-members">
                        <li>
                            <div class="row">
                                <div class="col-xs-3">
                                    <div class="avatar">
                                        <img src="<?= $this->basePath() . '/img/paper-dashboard/faces/face-0.jpg'; ?>"
                                             alt="Circle Image"
                                             class="img-circle img-no-padding img-responsive">
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    DJ Khaled
                                    <br/>
                                    <span class="text-muted"><small>Offline</small></span>
                                </div>

                                <div class="col-xs-3 text-right">
                                    <btn class="btn btn-sm btn-success btn-icon"><i class="fa fa-envelope"></i>
                                    </btn>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="row">
                                <div class="col-xs-3">
                                    <div class="avatar">
                                        <img src="<?= $this->basePath() . '/img/paper-dashboard/faces/face-1.jpg'; ?>"
                                             alt="Circle Image"
                                             class="img-circle img-no-padding img-responsive">
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    Creative Tim
                                    <br/>
                                    <span class="text-success"><small>Available</small></span>
                                </div>

                                <div class="col-xs-3 text-right">
                                    <btn class="btn btn-sm btn-success btn-icon"><i class="fa fa-envelope"></i>
                                    </btn>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="row">
                                <div class="col-xs-3">
                                    <div class="avatar">
                                        <img src="<?= $this->basePath() . '/img/paper-dashboard/faces/face-3.jpg'; ?>"
                                             alt="Circle Image"
                                             class="img-circle img-no-padding img-responsive">
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    Flume
                                    <br/>
                                    <span class="text-danger"><small>Busy</small></span>
                                </div>

                                <div class="col-xs-3 text-right">
                                    <btn class="btn btn-sm btn-success btn-icon"><i class="fa fa-envelope"></i>
                                    </btn>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-8 col-md-7">
            <div class="card">
                <div class="header">
                    <h4 class="title">Cadastrar Animal</h4>
                </div>
                <div class="content">
                    <form method="post" action="<?= $url; ?>">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Numero</label>
                                    <input type="text" class="form-control border-input"
                                           placeholder="Numero" name="numero" value="">
                                </div>
                            </div>

                            <div class="col-md-6">
                             <div class="form-group">
                                <label for="sel1">Classificação</label>
                                    <select class="form-control" id="sel1" name="classificacao">
                                         <option>Primapara</option>
                                         <option>Multipara</option>
                                         <option>Novilha</option>
                                    </select>
                            </div>
                        </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Data do último Parto</label>
                                    <input type="date" class="form-control border-input" name="dataUltimoParto" placeholder="nome">
                                </div>
                            </div>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-info btn-fill btn-wd">Cadastrar</button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
