<?php

echo $this->inlineScript()
    ->prependFile($this->basePath() . '/js/datehelper.js');

$url = $this->url('app/animal', ['controller' => 'animal', 'action' => 'cadastrar']);
?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Cadastrar o Animal</h4>
                </div>
                <div class="content">
                    <form method="post" action="<?= $url; ?>">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Número do Animal</label>
                                    <input type="text" class="form-control border-input"
                                           placeholder="Somente números"
                                           name="numero"
                                           pattern="\d*"
                                           required
                                           oninvalid="this.setCustomValidity('Insira um número válido!')"
                                           oninput="setCustomValidity('')"/>

                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="sel1">Classificação</label>
                                    <select class="form-control border-input" id="sel1" name="classificacao">
                                        <option>Novilha</option>
                                        <option>Primípara</option>
                                        <option>Multípara</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Data do Último Parto</label>
                                    <input type="text"
                                           class="form-control border-input validate-date"
                                           name="dataUltimoParto"
                                           placeholder="Dia/Mês/Ano"
                                           data-mask="00/00/0000"
                                           oninvalid="this.setCustomValidity('Insira uma data válida no formato: Dia/Mês/Ano')"
                                           oninput="setCustomValidity('')"
                                           disabled
                                           required/>
                                </div>
                            </div>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-info btn-fill btn-wd">Cadastrar</button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(function ($) {
        $("[name='classificacao']").change(function () {
            if ($(this).val() != "Novilha")
                $("[name='dataUltimoParto']").removeAttr('disabled');
            else
                $("[name='dataUltimoParto']").attr('disabled', true);
                 $("[name='dataUltimoParto']").val('');
        });
    });
</script>

