<?php $url = $this->url('app/animal', ['controller' => 'animal', 'action' => 'editar']); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Editar o Animal</h4>
                </div>
                <div class="content">
                    <form method="post" action="<?= $url; ?>">
                        <input type="hidden" value="<?= $animal->getId(); ?>" name="id">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Número do Animal</label>
                                    <input type="text" class="form-control border-input"
                                           placeholder="Somente números"
                                           name="numero"
                                           pattern="\d*"
                                           required
                                           oninvalid="this.setCustomValidity('Insira um número válido!')"
                                           oninput="setCustomValidity('')"
                                           value="<?= $animal->getNumero(); ?>"
                                    />
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="sel1">Classificação</label>
                                    <select class="form-control border-input" id="sel1" name="classificacao">
                                        <option hidden value="<?= $animal->getClassificacaoId(); ?>"><?= $animal->getClassificacao(); ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Data do Último Parto</label>
                                    <input type="text"
                                           class="form-control border-input validate-date"
                                           name="dataUltimoParto"
                                           placeholder="Dia/Mês/Ano"
                                           data-mask="00/00/0000"
                                           oninvalid="this.setCustomValidity('Insira uma data válida no formato: Dia/Mês/Ano')"
                                           oninput="setCustomValidity('')"
                                           disabled
                                           required
                                           value="<?= \Application\Helper\Data::dataToString($animal->getDataUltimoParto()); ?>"
                                    />
                                </div>
                            </div>
                        </div>

                        <div class="text-center">
                            <a type="button" onclick="window.history.back()"
                               class="btn btn-info btn-fill btn-wd" style="margin: 3%">Cancelar</a>
                            <button type="submit" class="btn btn-info btn-fill btn-wd" style="margin: 3%">Confirmar
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
echo $this->inlineScript()
    ->prependFile($this->basePath() . '/js/animal/animal-editar.js')
?>