<?php

echo $this->inlineScript()
    ->prependFile($this->basePath() . '/js/datehelper.js');

$url = $this->url('app/animal', ['controller' => 'animal', 'action' => 'editar']);
?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Editar o Animal</h4>
                </div>
                <div class="content">
                    <form method="post" action="<?= $url; ?>">
                        <input type="hidden" value="<?= $animal->getId(); ?>" name="id">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Número do Animal</label>
                                    <input type="text" class="form-control border-input"
                                           placeholder="Somente números"
                                           name="numero"
                                           pattern="\d*"
                                           required
                                           oninvalid="this.setCustomValidity('Insira um número válido!')"
                                           oninput="setCustomValidity('')"
                                           value="<?= $animal->getNumero(); ?>"
                                    />
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="sel1">Classificação</label>
                                    <select class="form-control border-input" id="sel1" name="classificacao"
                                            value="<?= $animal->getClassificacao(); ?>">
                                        <option><?= $animal->getClassificacao(); ?></option>
                                        <option style="display: none">Novilha</option>
                                        <option style="display: none">Primípara</option>
                                        <option style="display: none">Multípara</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Data do Último Parto</label>
                                    <input type="text"
                                           class="form-control border-input validate-date"
                                           name="dataUltimoParto"
                                           placeholder="Dia/Mês/Ano"
                                           data-mask="00/00/0000"
                                           oninvalid="this.setCustomValidity('Insira uma data válida no formato: Dia/Mês/Ano')"
                                           oninput="setCustomValidity('')"
                                           disabled
                                           required
                                           value="<?= $animal->dataUltimoPartoToString(); ?>"
                                    />
                                </div>
                            </div>
                        </div>

                        <div class="text-center">
                            <a type="button"
                               href="<?= $this->url('app/animal', array('controller' => 'index', 'action' => 'index')); ?>"
                               class="btn btn-info btn-fill btn-wd" style="margin: 3%">Cancelar</a>
                            <button type="submit" class="btn btn-info btn-fill btn-wd" style="margin: 3%">Confirmar
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(function ($) {
        $("[name='classificacao']").change(function () {
            if ($(this).val() != "Novilha")
                $("[name='dataUltimoParto']").removeAttr('disabled');
            else {
                $("[name='dataUltimoParto']").attr('disabled', true);
                $("[name='dataUltimoParto']").val('');
            }

        });

        var $select = $("#sel1");
        var classificao = $("option:selected", $select).text();

        switch (classificao) {
            case 'Novilha':
                $select.find('option:contains("Primípara")').show();
                $select.find('option:contains("Multípara")').show();
                break;
            case 'Primípara':
                $select.find('option:contains("Novilha")').show();
                $select.find('option:contains("Multípara")').show();
                break;
            case 'Multípara':
                $select.find('option:contains("Novilha")').show();
                $select.find('option:contains("Primípara")').show();
                break;
        }
    });
</script>

