<?php echo $this->render("cadastrar.phtml"); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Todos os Animais</h4>
                </div>
                <div class="content">
                    <table id="animais" class="table table-hover display" style="width:100%">
                        <thead>
                        <tr>
                            <th hidden>#</th>
                            <th>Número</th>
                            <th>Classificação</th>
                            <th>Estado</th>
                            <th>Dias Desde o Último Parto</th>
                            <th hidden>Dias Desde o Último Parto - Sort</th>
                            <th>Opções</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php foreach ($animais as $animal) { ?>
                            <tr>
                                <td hidden><?= $animal->getId(); ?></td>
                                <td><?= $animal->getNumero(); ?></td>
                                <td><?= $animal->getClassificacao(); ?></td>
                                <td><?= $animal->getEstado(); ?></td>
                                <td><?= $animal->getDiasDesdeUltimoParto(); ?></td>
                                <td hidden>
                                    <?php
                                    if ($animal->getDiasDesdeUltimoParto() == "-")
                                        echo "9999";
                                    else
                                        echo $animal->getDiasDesdeUltimoParto();
                                    ?>
                                </td>
                                <td>
                                    <a type="button"
                                       href="<?= $this->url('app/animal', ['action' => 'editar', 'id' => $animal->getId()]) ?>"
                                       class="btn btn-info btn-fill">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </a>

                                    <a href="<?= $this->url('app/animal', ['action' => 'remover', 'id' => $animal->getId()]) ?>"
                                       class="btn btn-danger btn-fill">
                                        <i class="fa fa-trash" aria-hidden="true" type="hidden"></i>
                                    </a>
                                </td>
                            </tr>

                        <?php } ?>


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(function ($) {
        $('#animais').DataTable({
            columnDefs: [
                { "orderable": false, "targets": 6 },
                {targets: '_all', className: 'dt-center'},
                { "orderData":[ 5 ],   "targets": [ 4 ] },
            ],
            order: [[1, 'desc']],
            paging: false
        });

        $('#animais_filter label input').addClass('form-control border-input');
    });
</script>
